title: bhawana is a codder
author: GitHub User
email: bhawana121998@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 bhawana is an awesome person .
 who is full of life and wants to life her life at fullest without any regrets 
yeah baby
...
# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
